version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: eslint
          command: yarn eslint
  build_and_push:
      machine: true
      steps:
        - checkout
        - run:
            name: build and push Docker image
            command: |
              docker build -t kcc112/publications-service:latest .
              echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
              docker push kcc112/publications-service:latest

workflows:
  base:
    jobs:
      - test:
          filters:
            branches:
              only:
                - ci
      - build_and_push:
          requires:
            - test
          filters:
              branches:
                only:
                  - ci